### ISSUE TITLE
Thoughts on cldr_territories

### ISSUE THREAD

**Issue by kipcole9** [Schultzer/cldr_territories#1]
@Schultzer Really appreciate your collaboration on this. 

### What CLDR provides

There are four sources of data that CLDR provides:

* Territory containment (common across all locales).  The source data is in the [cldr repo](https://github.com/kipcole9/cldr) as a submodule from https://github.com/unicode-cldr/cldr-core/blob/c48314ac492abd6498875eed9e68524e92684bf2/supplemental/territoryContainment.json
* Territory Information (common across all locales) The source data is in the [cldr repo](https://github.com/kipcole9/cldr) as a submodule from https://github.com/unicode-cldr/cldr-core/blob/c48314ac492abd6498875eed9e68524e92684bf2/supplemental/territoryInfo.json
* Localised territory names. The source data is in the [cldr repo](https://github.com/kipcole9/cldr) as a submodule from (using english as an example) https://github.com/unicode-cldr/cldr-localenames-full/blob/6da7f01576bbf5116fe5f73071c6e5c30d6437ea/main/en/territories.json
* Subdivision data which contains territory names below the "country" level which is not in the ex_cldr repo.

### What cldr_territories could provide 

1. Localised territory names - which is where you have started.  These names are only available for "country" level names (not subdivisions)
2. Territory includes - which would return the territories within a given territory.  The repo includes only country level data.  CLDR also includes subdivisions - some work would be required by me to include it.
3. Territory parent - the parent of the given territory - same as for inclusion
4. Territory info - returns the population, GDP, language usage etc from territory info - this isn't locale specific

### API thoughts

Just some ideas for discussion (based upon the Twitter ruby cldr implementation to which we have both referred):

```elixir
# Return a map of all known territories in the given locale
# @spec Cldr.Territory,known_territories(Cldr.Locale.name) :: %{territory_code: String.t, ...}
iex> Cldr.Territory.known_territories(locale \\ Cldr.get_current_locale)
%{"001": "World", TL: "East Timor", TM: "Turkmenistan", ...}

# Return the territory name for a given territory code
# @spec Cldr.Territory.from_territory_code(territory_code, options] :: String.t
iex> Cldr.Territory.from_territory_code(:GB, locale: "en")
"UK"

# Get the territories parents.  Note that a territory
# may have more than one parent
# @spec Cldr.Territory.parent(locale_name, options) :: [territory_code, ...]
iex> Cldr.Territory,parent(:GB)
[:EU, :"154"]

# Get territory subdivision
# @spec Cldr.Territory.contains(locale_name, options) :: [territory_code, ...]
iex> Cldr.Territory.contains(:EU)
[:AT, :BE, :CY, :CZ, :DE, :DK, ...]

# and for a subdivision below country.  A few challenges here:
# 1. Work required (by me) to have the data provided in the repo and in ex_cldr
# 2. Localised data (beyond english) is very sparse
# 3. The data is not hierarchical - for example it mixes (for GB) county and city names
# Personally I think this may be better deferred until a later release
# @spec Cldr.Territory.contains(territory_code) :: [subdivision_code :: String.t, ...]
iex> Cldr.Territory.contains(:GB)
["gbeaw", "gbeng", "gbgbn", "gbnir", "gbsct", "gbukm", ...]

# Get the territory info
# @spec Cldr.Territory.info(territory_code) :: Map.t
iex> Cldr.Territory.info(:GB)
%{gdp: 2788000000000, literacy_percent: 99, population: 64430400, ...}
```

Thoughts?

**Comment by Schultzer** [comment]
@kipcole9 Thanks for the feedback I like it so far as I see it with your propose implemented then we pretty much got everything covered.

**Comment by kipcole9** [comment]
I added today the localised territory names to the master branch of cldr.  Its accessed by `Cldr.Config.get_locale(locale_name) |> Map.get(:territories)`.  I will be adding localised language names later today my time.

**Comment by Schultzer** [comment]
@kipcole9 that's great work ❤️  I've conformed to your work and everything is working.
I still want to do some more testing so far I plan on a release there follows `ex_cldr` 1.0 release. 
I've made an issue #2 with a checklist of what I need to do before release will free to add to it.

and let me know what you think of the project so far 😄
