### ISSUE TITLE
1.0 release 

### ISSUE THREAD

**Issue by Schultzer** [Schultzer/cldr_territories#2]
This is whats need to be done for the `1.0` release.

- [x] update `mix.exs` to depend on `{:ex_cldr "~> 1.0"}`
- [x] write release notes
- [x] add `CHANGELOG.md`

**Comment by kipcole9** [comment]
The Elixir license is Apache 2.0 and I copied that strategy for Cldr to be in alignment.  I notice you specify the MIT license which of course is your choice.  Your thoughts?

**Comment by Schultzer** [comment]
I prefer MIT, due to it being short and easy to understand. 😄
