### ISSUE TITLE
Q: Short format for subdivisions

### ISSUE THREAD

**Issue by DaTrader** [Schultzer/cldr_territories#21]
@Schultzer @kipcole9 

In my use-case there's a need for abbreviated US state names and I don't see the ex_cldr_territories supporting this. Those are considered subdivisions in CLDR so I wonder if you guys have any intention to add the subdivision abbreviations in the future, for if not, I'll do it in my app on an on-demand basis.

For the time being I'm simply splitting the "us" prefix from the rest of the subdivision string and using the remaining part in upper case. This works for the US subdivision codes as they derive from the state name abbreviations, but it certainly won't work with I'd say vast majority of other territories and their subdivisions.

I'd also like to hear your thoughts on this one in general.

Thanks,

Damir

**Comment by Schultzer** [comment]
I don’t see any issue adding this, if it’s part of the CLDR dataset.

if the former is not the case then we would probably have to retrieve the data from Wikipedia.

**Comment by DaTrader** [comment]
Is this the link?

https://unicode-org.github.io/cldr-staging/charts/37/supplemental/index.html

**Comment by Schultzer** [comment]
> Is this the link?
> 
> https://unicode-org.github.io/cldr-staging/charts/37/supplemental/index.html

Yeah, but looking at the data then it might not be the best idea to support this generally, looks like it would lead to more confusion using the code instead of the subdivision. If your app only deals with US then I see the benefit.

Since I’m not an expert on subdivisions then I don’t know if an Albanian would be able to identify that Berat County would be 01.

In general, I believe it’s better to display the subdivision.

**Comment by DaTrader** [comment]
Yes, that's what I was referring to when I said displaying the remaining part of the subdivision wouldn't work with most territories/subdivisions.

**Comment by Schultzer** [comment]
I think a better user experience would be to display the translation rather than a subdivision code; By using the subdivision code to retrieve a translated string in any of the supported locales e.g. New York, then you avoid having to decide to display `USNY` or `NY`.
