### ISSUE TITLE
Loosen the cldr version requirement

### ISSUE THREAD

**Issue by LostKobrakai** [Schultzer/cldr_territories#4]
I think the base of cldr is stable enough to have `{:ex_cldr, "~> 1.0"}` instead of `{:ex_cldr, "~> 1.0.0"}`. This way one can use 1.2 without the need to override the version requirements for all packages.

**Comment by Schultzer** [comment]
Thanks @LostKobrakai

Fixed in [`1.1.3`](https://github.com/Schultzer/cldr_territories/commit/731d9bccd4f264aac34a5284a29ff050a9521893)
