### ISSUE TITLE
CLDR version 33 data is release

### ISSUE THREAD

**Issue by kipcole9** [Schultzer/cldr_territories#6]
Unicode Consortium released [CLDR version 33](http://cldr.unicode.org/index/downloads/cldr-33) today and I have updated `ex_cldr`, `ex_cldr_numbers`, `ex_cldr_lists`, ex_cldr_dates_times`, `ex_units` and `ex_money` to use the new data.

There aren't any new locales but I can see there are changes and additions to territory information.  I found this upgrade to have no issues in any of my code so hopefully the same for you.

Just bump your version requirements to `{ex_cldr, "~> 1.5.0}` and hopefully you're good to go.

**Comment by Schultzer** [comment]
[`0d733c0`](https://github.com/Schultzer/cldr_territories/commit/0d733c0f9ae72ec44a2d59f75b55c06b8f428dc9)

I've release a new version, great work Kip.
